### ISSUE TITLE
Memory graph overlapping

### ISSUE THREAD

**Issue by thatcosmonaut** [pfirsich/jprof#14]
First of all, thank you for this incredible tool, it has helped me optimized my love2d framework enormously. 

When switching to the memory graph type, adjacent boxes draw on top of each other so you can't tell them apart. 

Demonstration:
![example screenshot](https://i.imgur.com/HyKrXbl.png)

**Comment by pfirsich** [comment]
Hey, so sorry for the late reply. I am not really working on/with that tool anymore (started working after uni a short while ago). Can you share an example capture, so I can immediately reproduce and look into it? Thanks a lot for the report!
