### ISSUE TITLE
Incompatible with hump.gamestate

### ISSUE THREAD

**Issue by KayleMaster** [pfirsich/jprof#2]
Which is an often used library.
EDIT: look below for more details and a fix

**Comment by pfirsich** [comment]
I appreciate the tip, but you need to get into more detail for me to address that issue. What parts are incompatible? Can you make a minimal example that I can try to get working? Can someone else, who actually used hump.gamestate confirm, that the problem is not on @KayleMaster 's end?

**Comment by KayleMaster** [comment]
I've found a way to fix it actually, I have to modify love.run instead of love.update. I'm not aware of gamestate's internals so this was the best I could do:
```
...
prof.enabled(true)
prof.push('frame')
if love.update then love.update(dt) end -- will pass 0 if love.timer is disabled 
prof.pop('frame')
prof.enabled(false)
...
```
Thanks for the quick response anyways!

Regarding to gamestate, I tried the frame code in game:update(dt) but I got an error: `` Error: main.lua:48: attempt to index local 'top' (a nil value)``
```lua
function game:update(dt)
     prof.enabled(true)
     prof.push("update")

        prof.push("core")
        core.update()
        prof.pop("core")

        prof.push("objects")
        objects.update()
        prof.pop("objects")

        prof.push("BuildContr")
        _G.BuildController:update()
        prof.pop("BuildContr")

        prof.push("Finder")
        _G.finder:update()
        prof.pop("Finder")
        
        prof.push("ThreadError")
        local error = thread:getError()
        assert( not error, error )
        prof.pop("ThreadError")
    
    prof.pop("update")
    prof.enabled(false)
end
```
Sorry for the 'no details' post. I usually don't get so fast replies or any replies. I'm still waiting on that issue with busted for months and no one even replied.

**Comment by pfirsich** [comment]
I think the error message jprof gave you is really bad and absolutely not helping. I will reopen the issue and I will try to get to fixing that soon-ish!

**Comment by pablomayobre** [comment]
Just to leave this message fixed somewhere I will write what I said over at Discord:

Try calling `jprof.write` without pushing anything to the profiler and then open the file with the viewer and see if a similar error appears

**Comment by KayleMaster** [comment]
And here's the error to that as well:
``Error: main.lua:246: attempt to index global 'currentFrame' (a nil value)``
